export const GLOSSARY: Record<string, string> = {
  'Umsatzsteuer': 'VAT — the tax you collect from customers and pay to the Finanzamt',
  'MwSt': 'Mehrwertsteuer — same as Umsatzsteuer, the German VAT',
  'Vorsteuer': 'Input VAT — the VAT you paid on your purchases, which you can deduct',
  'Einkommensteuer': 'Income tax — tax on your profit as a self-employed person',
  'Gewerbesteuer': 'Trade tax — local business tax paid to your municipality',
  'Steuerrücklage': 'Tax reserve — money you set aside to pay your taxes later',
  'Finanzamt': 'German tax authority — the office you pay taxes to',
  'Privatentnahme': 'Money you take from your business for personal use',
  'Betriebsausgaben': 'Business expenses — costs you can deduct from your profit',
  'Betriebseinnahmen': 'Business income — all money your business receives',
  'EÜR': 'Einnahmen-Überschuss-Rechnung — simple profit and loss statement for freelancers',
  'Kleinunternehmer': 'Small business owner exempt from VAT under §19 UStG',
  'Regelbesteuerung': 'Standard VAT taxation — you charge and reclaim VAT normally',
  'Schätzung': 'Tax estimation — Finanzamt estimates your taxes if you don\'t file',
  'ELSTER': 'Official German tax filing portal — where you submit your tax returns',
  'Steuerberater': 'Tax advisor — professional who helps with your German tax filings',
  'Bürgergeld': 'German basic income support — formerly called Hartz IV',
  'EKS': 'Einkommens-Kurzübersicht — income estimate you give to the Jobcenter',
  'IKS': 'Ist-Kosten-Nachweis — actual income statement you give to the Jobcenter',
  'Freibetrag': 'Tax-free allowance — amount of income exempt from tax calculation',
  'Offene Forderung': 'Outstanding invoice — money a customer owes you',
  'Verbindlichkeit': 'Liability — money you owe to a supplier or creditor',
  'Fixkosten': 'Fixed costs — regular monthly expenses like rent and subscriptions',
  'Bruttobetrag': 'Gross amount — total including VAT',
  'Nettobetrag': 'Net amount — amount without VAT',
  'Tagesabschluss': 'Daily close — end of day cash reconciliation',
}
