export const GLOSSARY: Record<string, string> = {
  'Umsatzsteuer': 'VAT — the tax added to your invoices. You collect it from customers and pass it on to the Finanzamt.',
  'MwSt': 'Mehrwertsteuer — the same as Umsatzsteuer. Both mean VAT in German.',
  'Vorsteuer': 'VAT you paid on your own business purchases. You can deduct this from the VAT you owe the Finanzamt.',
  'Einkommensteuer': 'Income tax — tax on your profit as a self-employed person. Paid once a year.',
  'Gewerbesteuer': 'Trade tax — a local business tax paid to your municipality. Not all freelancers owe this.',
  'Steuerruecklage': 'Tax reserve — money you set aside now so you can pay your taxes later without stress.',
  'Steuerrücklage': 'Tax reserve — money you set aside now so you can pay your taxes later without stress.',
  'Finanzamt': 'The German tax office — the authority you pay your taxes to.',
  'Privatentnahme': 'Money you transfer from your business to yourself for personal use — like paying yourself.',
  'Betriebsausgaben': 'Business expenses — costs you can deduct from your income to reduce your taxable profit.',
  'Betriebseinnahmen': 'Business income — all money your business receives from customers.',
  'EUER': 'Simple profit and loss summary used by freelancers and small businesses in Germany. Shows income minus expenses.',
  'EÜR': 'Simple profit and loss summary used by freelancers and small businesses in Germany. Shows income minus expenses.',
  'Kleinunternehmer': 'A small business owner with under 22,000 EUR yearly revenue who is exempt from charging VAT.',
  'Regelbesteuerung': 'Standard VAT rules — you charge VAT on invoices and can reclaim VAT on purchases.',
  'Schaetzung': 'If you do not file your taxes, the Finanzamt estimates what you owe — usually more than the real amount.',
  'Schätzung': 'If you do not file your taxes, the Finanzamt estimates what you owe — usually more than the real amount.',
  'ELSTER': 'The official German online portal for submitting your tax returns.',
  'Steuerberater': 'A tax advisor — a professional who helps you with German tax filings and planning.',
  'Buergergeld': 'German basic income support (previously called Hartz IV) — monthly support for people with low or no income.',
  'Bürgergeld': 'German basic income support (previously called Hartz IV) — monthly support for people with low or no income.',
  'EKS': 'Einkommens-Kurzuebersicht — the estimated income statement you give to the Jobcenter at the start of a period.',
  'IKS': 'Ist-Kosten-Nachweis — the actual income statement you give to the Jobcenter after a period ends.',
  'Freibetrag': 'An amount of income that is exempt from tax or benefit calculations — you keep this money in full.',
  'Offene Forderung': 'An unpaid invoice — money a customer owes you but has not yet paid.',
  'Verbindlichkeit': 'Money you owe — to a supplier, service provider, or creditor.',
  'Fixkosten': 'Fixed costs — regular monthly expenses like rent and subscriptions that stay the same each month.',
  'Bruttobetrag': 'Gross amount — the total price including VAT.',
  'Nettobetrag': 'Net amount — the price without VAT.',
  'Tagesabschluss': 'Daily close — an end-of-day check to confirm your cash balance matches your records.',
}
